% treatments
arg(offer(a1,s1)).
arg(offer(a2,s1)).
arg(offer(c,s1)).

% attacks
att(offer(a1,s1),offer(a2,s1)).
att(offer(a2,s1),offer(a1,s1)).

att(offer(a1,s1),offer(c,s1)).
att(offer(c,s1),offer(a1,s1)).

att(offer(a2,s1),offer(c,s1)).
att(offer(c,s1),offer(a2,s1)).

% query: ./dlv ground.dl IJCAI/baula-v1-sketch.dl -filter=in
% output: {}

% query: ./dlv prefex.dl IJCAI/baula-v1-sketch.dl -filter=in
% output: 

%{in(offer(c,s1))}

%{in(offer(a2,s1))}

%{in(offer(a1,s1))}




