version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
    command: ["./wait-for-it.sh", "--timeout=0", "data-miner_webapp_1:3006", "--", "nginx", "-g", "daemon off;"]
    tty: true
    depends_on:
      - webapp
    ports:
      - '443:443'
      - '80:80'

  webapp:
    build:
      context: .
    environment:
      R_ENV: production
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: dataHistory
      MYSQL_HOST: data-miner_mariadb_1
    depends_on:
      - mariadb

  mariadb:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dataHistory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - processing_data_volume:/var/lib/mysql

volumes:
  processing_data_volume:

networks:
  default:
    #external:
      name: processing_network
