version: "3.7"

services:

  # Uncomment for service discovery:

  #consul-service:
    #image: gliderlabs/consul-server
    #command: "--bootstrap"
    #ports:
      #- 8500:8500
    #restart: "no"

  #registrator:
    #image: gliderlabs/registrator
    #command: "consul://consul-service:8500"
    #volumes:
      #- /var/run/docker.sock:/tmp/docker.sock
    #links:
      #- consul-service
    #depends_on:
      #- consul-service
    #restart: "no"

  proxy:
    build:
      context: ./proxy
    depends_on:
      - webapp
    command: ["./wait-for-it.sh", "--timeout=0", "message-passer_webapp_1:3005", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '443:443'
      - '80:80'

  webapp:
    build:
      context: .
    command: ["./wait-for-it.sh", "--timeout=0", "message-passer_template-server_1:8080", "--", "npm", "start"]
    depends_on:
      - template-server
    environment:
      # Under single docker machine (i.e. single host) use allocated hostname of single proxy handling all routing (e.g. device-integration_nokia_proxy_1), otherwise use machine (host) addresses.
      - FHIR_SERVER_ADDRESS=192.168.99.101
      - DNC_ADDRESS=192.168.99.102
      - PROCESSING_ADDRESS=192.168.99.103

  template-server:
    image: big-kcl/template-server:latest
    #ports:
      #- 8080:8080
    depends_on:
      #- consul-service
      - neo4j

  neo4j:
    image: neo4j
    environment:
      - NEO4J_AUTH=neo4j/12345
    volumes:
      - dnc_volume:/data

volumes:
  dnc_volume:

networks:
  default:
    external:
      name: dnc_network
