version: "3.7"

services:

  webapp:
    build:
      context: .
    environment:
      - DNC_ADDRESS=danvers
      - UI_ADDRESS=192.168.99.105
    restart: unless-stopped

  proxy:
    build:
      context: ./proxy
    tty: true
    depends_on:
      - webapp
    ports:
      - '443:443'
      - '80:80'
    restart: unless-stopped

volumes:
  dnc_volume:

networks:
  default:
    name: dnc_network
