version: "3.0"

services:

  webapp:
    build:
      context: .
    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306

  migration:
    image: device-integration_garmin_webapp:latest
    command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]
    links:
      - mysql
    depends_on:
      - mysql
