version: "3.0"

services:

  webapp:
    build:
      context: .
    links:
      - mysql
    depends_on:
      - mysql
    ports:
      - 3000:3000

  mysql:
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - data_volume:/var/lib/mysql

  migration:
    image: device-integration_garmin_webapp:latest
    command: ["./wait-for-it/wait-for-it.sh", "mysql:3306", "--", "npm", "run", "migrate"]
    links:
      - mysql
    depends_on:
      - mysql

  proxy:
    build:
      context: ./proxy
    tty: true
    links:
      - webapp
    ports:
      - '443:443'
      - '80:80'
volumes:
  data_volume:
