version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
    command: ["./wait-for-it.sh", "--timeout=0", "data-miner_webapp_1:3006", "--", "nginx", "-g", "daemon off;"]
    tty: true
    depends_on:
      - webapp
    ports:
      - '3006:443'

  webapp:
    build:
      context: .

volumes:
  processing_data_volume:

networks:
  default:
    #external:
      name: network
      ipam:
        driver: default
        config:
          - subnet: 172.22.0.0/16
