version: "3.7"

services:

  webapp-queue:
    image: "consult-kcl/sensor-fhir-mapper_queue"
    build:
      context: .
    command: ["./wait-for-it.sh", "--timeout=0", "sensor-fhir-mapper_rabbit_1:15672", "--", "npm", "run", "consume"]
    depends_on:
      - rabbit
    environment:
      - FHIR_SERVER_ADDRESS=romanova
      - NODE_EXTRA_CA_CERTS=/consult.crt
    extra_hosts:
      # If fhir server at IP rather than known host, name on fhir server's certificate : fhir server IP.
      romanova: 10.0.1.196

  rabbit:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    volumes:
      - data_volume:/var/lib/rabbitmq

volumes:
  data_volume:

networks:
  default:
    name: device_network
