version: "3.7"

services:

  proxy:
    build:
      context: ./proxy
    command: ["./wait-for-it.sh", "--timeout=0", "device-integration_nokia_webapp_1:3000", "--", "nginx", "-g", "daemon off;"]
    tty: true
    ports:
      - '443:443'
      - '80:80'
    depends_on:
      - webapp
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    restart: unless-stopped

  webapp:
    build:
      context: .
    depends_on:
      - mariadb
    restart: unless-stopped

  migration:
    image: device-integration_nokia_webapp:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: ["./wait-for-it.sh", "--timeout=0", "device-integration_nokia_mariadb_1:3306", "--", "npm", "run", "migrate"]
    depends_on:
      - webapp
      - mariadb

  mariadb:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - sensor_data_volume:/var/lib/mysql
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - proxy
    command: certonly --webroot --webroot-path=/var/www/html --email martin.chapman@kcl.ac.uk --agree-tos --no-eff-email --force-renewal -d device.consultsystem.co.uk

volumes:
  sensor_data_volume:
  certbot-etc:
  certbot-var:
  web-root:

networks:
  default:
    external:
      name: device_network
