version: "3.7"

services:

  template-server:
    image: kclhi/template-server:latest
    ports:
      - 8081:8080
    depends_on:
      - neo4j

  neo4j:
    image: neo4j:3.4
    environment:
      NEO4J_AUTH: ${NEO4J_AUTH}
    volumes:
      - dnc_volume:/data

  phpldapadmin:
    image: osixia/phpldapadmin:latest
    depends_on:
      - openldap
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_SERVER_PATH: ${PHPLDAPADMIN_SERVER_PATH}
      PHPLDAPADMIN_HTTPS: ${PHPLDAPADMIN_HTTPS}
      PHPLDAPADMIN_LDAP_HOSTS: ${PHPLDAPADMIN_LDAP_HOSTS}
    ports:
      - 8082:80
      - 8083:443

  openldap:
    build:
      context: ldap
    image: kclconsult/openldap:latest
    command: --loglevel debug
    environment:
      LDAP_TLS: "false"
      LDAP_ORGANISATION: ${LDAP_ORGANISATION}
      LDAP_DOMAIN: ${LDAP_DOMAIN}
      LDAP_BASE_DN: ${LDAP_BASE_DN}
      LDAP_ADMIN_PASSWORD: ${LDAP_ADMIN_PASSWORD}
    volumes:
      - ldap_volume:/var/lib/ldap
      - ldap_volume:/etc/ldap/slapd.d
    ports:
      - 389:389
      - 636:636

volumes:
  dnc_volume:
  ldap_volume:
