% general facts about the patient
% comes from csv

% t1
suffers_from(bob,backpain,t1).

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% static information

% ASPT argument scheme -- goal is reduce pain, facts do not change the outcome.
a(aspt([goal(G), action(A,T), promotes(A,G)],action(A,T))) :- goal(G), action(A,T), promotes(A,G).

% nhs painkillers guideline
action(ibuprofen,T) :- suffers_from(Patient,backpain,T).
goal(rp) :- action(ibuprofen,T).
promotes(ibuprofen,rp):- action(ibuprofen,T).
