1. When we use grounded semantics for the example, there are no IN action, because ibuprofen is never excluded at any point.

When we ask for alternatives for ibuprofen:
-- a new metaargument attacking ibuprofen?

OR/AND 

when using preferred semantics:
post-processing of the extensions is required to get the desired extension (e.g. extensions that satisfy all the goals).

2. we are not representing the questions now. 


